### ISSUE TITLE
Map shows inverted

### ISSUE THREAD

**Issue by Adesubomi** [Adesubomi/jquery-mapael-nigeria#2]
Created the map with inkscape, followed the instructions on the link below step by step. But the map still displays inverted, and display area is not properly set. Any help will b appreciated
@neveldo

https://www.vincentbroute.fr/mapael/create-map.php

**Comment by Adesubomi** [comment]
Issue fixed on [584c091](https://github.com/Adesubomi/jquery-mapael-nigeria/commit/584c091719b484cde683732352a10b23ae611241)

**Comment by neveldo** [comment]
Hello @Adesubomi ,

I'm glad you solved your issue ! For my information, what was the issue ? Did you found a solution through inkscape ?

**Comment by Adesubomi** [comment]
Yes, found help within inkscape. It happened that there were svg fragments outside the desired plot area. When I copied out the map area I wanted into a new svg file, all issues were resolved. Thank you @neveldo . I will add this map to [mapael-maps](https://github.com/neveldo/mapael-maps) once I'm done testing.

**Comment by neveldo** [comment]
Thanks for the explanation @Adesubomi , and many thanks for your incoming contribution !
